# Generated by Django 5.2.3 on 2025-06-30 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tithes", "Tithes"),
                            ("offerings", "Offerings"),
                            ("donations", "Donations"),
                            ("fundraising", "Fundraising"),
                            ("other_income", "Other Income"),
                            ("salaries", "Salaries"),
                            ("utilities", "Utilities"),
                            ("rent_mortgage", "Rent/Mortgage"),
                            ("missions", "Missions"),
                            ("benevolence", "Benevolence"),
                            ("supplies", "Supplies"),
                            ("maintenance", "Maintenance"),
                            ("events", "Events"),
                            ("other_expense", "Other Expense"),
                        ],
                        help_text="Select a category for the transaction.",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
